name: Follow upstream

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull&Merge upstream
        env:
          REPO_FORK: https://github.com/atsushi-ishibashi/repoA.git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote add upstream ${REPO_FORK}
          git fetch upstream
          diff_output=$(git log origin/main..upstream/main)
          if [[ ! -z "$diff_output" ]]; then echo "差分あり"; echo "DIFF_FOUND=true" >> "$GITHUB_ENV"; fi
      - name: diff exists
        if: ${{ env.DIFF_FOUND != '' }}
        run: |
          echo "差分あり"
          branch=upstream-$(git rev-parse --short upstream/main)
          git checkout -b ${branch} upstream/main
          git push origin ${branch}
      - name: no diff
        if: ${{ env.DIFF_FOUND == '' }}
        run: |
          echo "差分なし"
