name: Follow upstream

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull&Merge upstream
        env:
          REPO_FORK: https://github.com/atsushi-ishibashi/repoA.git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global pull.rebase merges

          git pull --unshallow

          git remote add upstream ${REPO_FORK}

          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          diff_output=$(git diff)
          if [[ ! -z "$diff_output" ]]; then echo "差分あり" else echo "差分なし" fi
